spring:
  profiles:
    active: dev

server:
  port: 8989

mybatis:
  config-location: classpath:spring/mybatisconfig.xml
  mapper-locations: classpath:mapper/**/*.xml
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/meizi?&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource